version: 0.0
os: linux
files:
- source: /DemoWebApp
  destination: /opt/apache-tomcat/webapps/DemoWebApp
hooks:
  AfterInstall:
    - location: target/scripts/stop-server.sh
      timeout: 180
    - location: target/scripts/start-server.sh
      timeout: 180
